"""crear tablas iniciales

Revision ID: 0ff6f7d53730
Revises: 
Create Date: 2026-08-16 23:09:06.338758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff6f7d53730'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identificador', sa.String(length=50), nullable=False),
    sa.Column('especie', sa.Enum('bovino', 'equino', 'ovino', 'otro', name='especie'), nullable=False),
    sa.Column('sexo', sa.Enum('macho', 'hembra', 'desconocido', name='sexo'), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador')
    )
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('timestamp_evento', sa.DateTime(), nullable=False),
    sa.Column('datos_raw', sa.JSON(), nullable=True),
    sa.Column('nivel_relevancia', sa.Enum('normal', 'media', 'alta', name='nivel_relevancia'), nullable=False),
    sa.Column('fuente', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('nivel', sa.Enum('baja', 'media', 'alta', name='nivel'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'revisada', 'descartada', name='estado'), nullable=False),
    sa.Column('analisis_ia', sa.JSON(), nullable=True),
    sa.Column('notificado_n8n', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table(
            'configuracion',
            sa.column('clave', sa.String()),
            sa.column('valor', sa.Text()),
            sa.column('descripcion', sa.Text()),
        ),
        [
            {'clave': 'umbral_confianza_alerta', 'valor': '0.75', 'descripcion': 'Confianza mínima para generar alerta'},
            {'clave': 'animales_minimos_hato', 'valor': '3', 'descripcion': 'Número mínimo esperado de animales en campo'},
            {'clave': 'ventana_inactividad_min', 'valor': '60', 'descripcion': 'Minutos sin detección para considerar ausencia'},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    op.drop_table('eventos')
    op.drop_table('configuracion')
    op.drop_table('animales')
    # ### end Alembic commands ###
